### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by theletterkilleth** [erwincoumans/DaisyCloudSeed#1]
Hi Erwin!

I too am interested in the notion of a sample player on the Daisy. One thing that I cannot find is an implementation of a FS. Most of the code seems to use standard "open" calls and the like. So I was wondering what I was missing...?

**Comment by erwincoumans** [comment]
the sample player in this repo is working fine

**Comment by theletterkilleth** [comment]
Yes, sorry, I didn't mean it to be an issue. I was just asking a question and there doesn't seem to be a private message option. Now I see that there is a fatfs include.

**Comment by erwincoumans** [comment]
No worry , it is best to use the forum at https://forum.electro-smith.com/
